In [3]:
%%file test_lab_3.py


from torch.nn.functional import conv_transpose2d
import pytest
import numpy as np
import torch


def generate_zeros(input, weight, stride, padding, output_padding):
    batch_size, in_channels, in_height, in_width = input.shape
    out_channels, in_channels, kernel_height, kernel_width = weight.shape
    H_out = (in_height - 1) * stride - 2 * padding + kernel_height + output_padding
    W_out = (in_width - 1) * stride - 2 * padding + kernel_width + output_padding
    output = np.zeros((batch_size, out_channels, H_out, W_out))
    return (batch_size, out_channels, H_out, W_out,
            in_channels, kernel_height,
            kernel_width, in_height, in_width, output)

def ConvolutionTranspose(input_data, weight_tensor, padding=0, dilation=1, stride=1, groups = 1):
    (batch_size, out_channels, H_out,
    W_out, in_channels,
    kernel_height, kernel_width,
    in_height, in_width, result) = generate_zeros(input_data, weight_tensor,
                                                       stride, padding,
                                                       padding)

    if padding > 0:
        input_data = np.pad(input_data, padding, mode='constant')

    result = np.zeros((batch_size, out_channels, H_out, W_out))

    for b in range(batch_size):
        for c in range(out_channels):
            for i in range(H_out):
                for j in range(W_out):
                    for k in range(in_channels):
                        for s in range(kernel_height):
                            for t in range(kernel_width):
                                ii = i + padding - s * dilation
                                jj = j + padding - t * dilation
                                if ii >= 0 and jj >= 0 and ii < in_height * stride and jj < in_width * stride and (ii % stride == 0) and (jj % stride == 0):
                                    ii //= stride
                                    jj //= stride
                                    result[b, c, i, j] += np.multiply(input_data[b, k, ii, jj], weight_tensor[c, k, s, t])
    return result




def test_1():
    image = torch.randn(1, 1, 3, 3)
    weight = torch.randn(1, 1, 3, 3)

    myConvT = torch.from_numpy(ConvolutionTranspose(image.numpy(), weight.numpy()))

    torchConvT = conv_transpose2d(image, weight)

    myConvT = myConvT.to(torchConvT.dtype)

    assert torch.allclose(myConvT, torchConvT)


def test_2():
    image = torch.randn(1, 1, 5, 5)
    weight = torch.randn(1, 1, 3, 3)

    myConvT = torch.from_numpy(ConvolutionTranspose(image.numpy(), weight.numpy()))

    torchConvT = conv_transpose2d(image, weight)

    myConvT = myConvT.to(torchConvT.dtype)

    assert torch.allclose(myConvT, torchConvT)

def test_3():
    image = torch.randn(1, 1, 5, 5)
    weight = torch.randn(1, 1, 3, 3)

    myConvT = torch.from_numpy(ConvolutionTranspose(image.numpy(), weight.numpy()))

    torchConvT = conv_transpose2d(image, weight)

    myConvT = myConvT.to(torchConvT.dtype)

    assert torch.allclose(myConvT, torchConvT)

def test_4():
    image = torch.randn(1, 1, 7, 7)
    weight = torch.randn(1, 1, 3, 3)

    myConvT = torch.from_numpy(ConvolutionTranspose(image.numpy(), weight.numpy()))

    torchConvT = conv_transpose2d(image, weight)

    myConvT = myConvT.to(torchConvT.dtype)

    assert torch.allclose(myConvT, torchConvT)

def test_5():
    image = torch.randn(1, 1, 9, 9)
    weight = torch.randn(1, 1, 5, 5)

    myConvT = torch.from_numpy(ConvolutionTranspose(image.numpy(), weight.numpy()))

    torchConvT = conv_transpose2d(image, weight)

    myConvT = myConvT.to(torchConvT.dtype)

    assert torch.allclose(myConvT, torchConvT)

Overwriting test_lab_3.py


In [4]:
!pytest

======================================= test session starts ========================================
platform linux -- Python 3.10.12, pytest-7.4.3, pluggy-1.3.0
rootdir: /content
plugins: anyio-3.7.1
collected 5 items                                                                                  

test_lab_3.py .....                                                                          [100%]

======================================== 5 passed in 4.13s =========================================


In [4]:
image = torch.randn(1, 1, 9, 9)
weight = torch.randn(1, 1, 5, 5)

myConvT = torch.from_numpy(ConvolutionTranspose(image.numpy(), weight.numpy()))
print("Результат выполнения моей функции ConvolutionTranspose:")
print(myConvT)

torchConvT = conv_transpose2d(image, weight)
print("Результат выполнения встроенной функции conv_transpose2d из библиотеки PyTorch:")
print(torchConvT)

myConvT = myConvT.to(torchConvT.dtype)


torch.allclose(myConvT, torchConvT)

Результат выполнения моей функции ConvolutionTranspose:
tensor([[[[ 9.4909e-01, -5.7451e-01,  8.9306e-01, -4.4602e-01, -6.0922e-01,
            5.4444e-01, -1.8029e+00, -1.2936e+00,  3.4492e-01,  1.4551e-01,
           -1.4501e-01, -9.6834e-02, -2.2440e-02],
          [-1.1759e-02, -1.9948e+00,  1.5880e+00,  1.2745e-01,  2.5963e+00,
           -2.5192e+00,  9.7891e-01,  1.0645e+00,  9.9230e-01,  1.5090e+00,
           -5.6474e-01,  5.3950e-02,  2.6525e-01],
          [ 7.4824e-02, -2.9715e+00, -2.1657e+00,  4.8301e+00,  3.0426e+00,
           -2.9415e+00,  8.1808e-01, -3.5283e+00, -1.0764e+00, -1.5699e+00,
            2.5184e+00,  1.3477e+00, -4.3205e-01],
          [-3.0911e+00,  2.4124e+00,  5.6406e+00,  8.7986e-01,  2.2736e+00,
            4.0089e+00, -4.3301e+00,  5.8070e+00, -7.3173e-01,  1.1121e+00,
            1.7933e+00, -1.3215e+00, -1.5420e+00],
          [-1.9157e+00,  1.5963e+00,  1.5566e+00, -3.1425e+00, -1.0240e+01,
            4.0715e+00,  1.9596e+00, -3.0293e+00,  2.171

True

через двумерную

In [36]:
from torch.nn.functional import conv_transpose2d
import pytest
import numpy as np
import torch
import sys
import os

def TranspConv2d(matrix, in_channels, out_channels, kernel_size, transp_stride=1, padding=0, dilation=1, bias=True, padding_mode='zeros'):
    stride = 1

    #добавление отступов и padding в входной матрице
    pad = kernel_size - 1
    result_matrix = []
    for matr in matrix:
      zero_tensor = np.zeros((((matr.shape[0]-1)*(transp_stride)+1), ((matr.shape[1]-1)*(transp_stride)+1)))
      for a in range (0, zero_tensor.shape[0], transp_stride):
        for b in range (0, zero_tensor.shape[1], transp_stride):
          zero_tensor[a][b] = matr[a//(transp_stride)][b//(transp_stride)]

      pad_matr = np.pad(zero_tensor, pad_width=pad, mode='constant')
      result_matrix.append(pad_matr)
    matrix = torch.tensor(result_matrix)

    #генерация bias
    if bias == True:
      bias_val = torch.rand(out_channels)
    else:
      bias_val = torch.zeros(out_channels)

    #padding_mode
    if (padding_mode == 'zeros'):
      pad = torch.nn.ZeroPad2d(padding)
      matrix = pad(matrix)
    if (padding_mode == 'reflect'):
      pad = torch.nn.ReflectionPad2d(padding)
      matrix = pad(matrix)
    if (padding_mode == 'replicate'):
      pad = torch.nn.ReplicationPad2d(padding)
      matrix = pad(matrix)
    if (padding_mode == 'circular'):
      pad = torch.nn.CircularPad2d(padding)
      matrix = pad(matrix)

    #генерация ядра
    filter = np.array(torch.rand(out_channels, in_channels, kernel_size, kernel_size))

    #инвертирование ядра для ConvTranspose2d
    filter_for_transpose = []
    for j in range(out_channels):
      filter_in = []
      for i in range(in_channels):
        filter_in.append(np.flip(np.array(filter[j][i])))
      filter_for_transpose.append(filter_in)

    filter_for_transpose = torch.tensor(filter_for_transpose)
    filter_for_transpose = filter_for_transpose.reshape(in_channels, out_channels, kernel_size, kernel_size)



    result = []
    for l in range(out_channels):
      feature_map = np.array([]) #генерация пустой feature-map
      for i in range (0, matrix.shape[1]-((filter.shape[2]-1)*dilation+1)+1, stride): #(filter.size - 1)*dilation + 1 при delation
        for j in range (0, matrix.shape[2]-((filter.shape[3]-1)*dilation+1)+1, stride):
          summa = 0
          for c in range (in_channels):
            val = matrix[c][i:i+(filter.shape[2]-1)*dilation+1:dilation, j:j+(filter.shape[3]-1)*dilation+1:dilation]
            mini_sum = (val*filter[l][c]).sum()
            summa = summa + mini_sum
          feature_map = np.append(feature_map, float(summa + bias_val[l])) #bias
      result.append(feature_map.reshape((matrix.shape[1]-((filter.shape[2]-1)*dilation+1))//stride+1, (matrix.shape[2]-((filter.shape[3]-1)*dilation+1))//stride+1))


    return np.array(result), torch.tensor(np.array(filter_for_transpose)), torch.tensor(np.array(bias_val))



tensor1 = torch.rand(3, 7, 10)

result, kernel, bias_val = TranspConv2d(tensor1, in_channels=3, out_channels=1, kernel_size=3, transp_stride=2, bias=True,)
torchFunction = torch.nn.ConvTranspose2d(in_channels=3, out_channels=1, kernel_size=3, stride=2, bias=True,)
torchFunction.weight.data = kernel
torchFunction.bias.data = bias_val

print(np.array_equal(torchFunction(tensor1).detach().numpy().astype("float16"), result.astype("float16")))

True


In [25]:
tensor1 = torch.rand(3, 4, 4)

result, kernel, bias_val = TranspConv2d(tensor1, in_channels=3, out_channels=1, kernel_size=3, transp_stride=2, bias=True,)
torchFunction = torch.nn.ConvTranspose2d(in_channels=3, out_channels=1, kernel_size=3, stride=2, bias=True,)
torchFunction.weight.data = kernel
torchFunction.bias.data = bias_val

print(np.array_equal(torchFunction(tensor1).detach().numpy().astype("float16"), result.astype("float16")))

True


In [26]:
tensor1 = torch.rand(3, 7, 9)

result, kernel, bias_val = TranspConv2d(tensor1, in_channels=3, out_channels=1, kernel_size=3, transp_stride=2, bias=True,)
torchFunction = torch.nn.ConvTranspose2d(in_channels=3, out_channels=1, kernel_size=3, stride=2, bias=True,)
torchFunction.weight.data = kernel
torchFunction.bias.data = bias_val

print(np.array_equal(torchFunction(tensor1).detach().numpy().astype("float16"), result.astype("float16")))

True


In [27]:
tensor1 = torch.rand(3, 16, 12)

result, kernel, bias_val = TranspConv2d(tensor1, in_channels=3, out_channels=1, kernel_size=3, transp_stride=2, bias=True,)
torchFunction = torch.nn.ConvTranspose2d(in_channels=3, out_channels=1, kernel_size=3, stride=2, bias=True,)
torchFunction.weight.data = kernel
torchFunction.bias.data = bias_val

print(np.array_equal(torchFunction(tensor1).detach().numpy().astype("float16"), result.astype("float16")))

True


In [28]:
tensor1 = torch.rand(3, 2, 3)

result, kernel, bias_val = TranspConv2d(tensor1, in_channels=3, out_channels=1, kernel_size=3, transp_stride=2, bias=True,)
torchFunction = torch.nn.ConvTranspose2d(in_channels=3, out_channels=1, kernel_size=3, stride=2, bias=True,)
torchFunction.weight.data = kernel
torchFunction.bias.data = bias_val

print(np.array_equal(torchFunction(tensor1).detach().numpy().astype("float16"), result.astype("float16")))

True


In [37]:
tensor1 = torch.rand(3, 2, 3)

result, kernel, bias_val = TranspConv2d(tensor1, in_channels=3, out_channels=1, kernel_size=3, transp_stride=2, bias=True,)
torchFunction = torch.nn.ConvTranspose2d(in_channels=3, out_channels=1, kernel_size=3, stride=2, bias=True,)
torchFunction.weight.data = kernel
torchFunction.bias.data = bias_val

print("Результат выполнения моей функции TranspConv2d:")
print(torchFunction(tensor1).detach().numpy().astype("float16"))
print()
print("Результат выполнения встроенной функции conv_transpose2d из библиотеки PyTorch:")
print(result.astype("float16"))
print(np.array_equal(torchFunction(tensor1).detach().numpy().astype("float16"), result.astype("float16")))

Результат выполнения моей функции TranspConv2d:
[[[0.9375 0.893  1.404  0.804  1.867  1.137  1.292 ]
  [0.8467 0.8027 1.222  0.7607 1.964  1.0625 1.254 ]
  [1.891  1.972  3.004  1.779  2.703  1.907  1.648 ]
  [1.587  1.121  1.672  0.74   0.954  0.6567 0.6445]
  [1.479  1.873  1.905  0.7817 1.089  1.2    1.067 ]]]

Результат выполнения встроенной функции conv_transpose2d из библиотеки PyTorch:
[[[0.9375 0.893  1.404  0.804  1.867  1.137  1.292 ]
  [0.8467 0.8027 1.222  0.7607 1.964  1.0625 1.254 ]
  [1.891  1.972  3.004  1.779  2.703  1.907  1.648 ]
  [1.587  1.121  1.672  0.74   0.954  0.6567 0.6445]
  [1.479  1.873  1.905  0.7817 1.089  1.2    1.067 ]]]
True
